services:

  aihealth-api:
    container_name: aihealth-api
    build:
      context: "."
      dockerfile: ./deployment/rest_server/Dockerfile
    image: aihealth-api:latest
    depends_on:
      - aihealth-redis
      - aihealth-postgres
      - aihealth-mongo
      - aihealth-clickhouse
    restart: no
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_ALGORITHM
      - JWT_SECRET
      - JWT_AUDIENCE
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_ASYNCPG_URL=${POSTGRES_ASYNCPG_URL}
      - POSTGRES_URL_SYNC=${POSTGRES_URL_SYNC}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

    volumes:
      - api_logs:/src/logs
      - api_data:/src

  aihealth-redis:
    container_name: aihealth-redis
    image: redis:alpine
    command:
      - "-- requirepass ${REDIS_PASSWORD}"
    restart: no
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  aihealth-postgres:
    container_name: aihealth-postgres
    image: postgres:alpine
    restart: no
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aihealth-mongo:
    container_name: aihealth-mongo
    image: mongo:latest
    restart: no
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  aihealth-clickhouse:
    container_name: aihealth-clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - 8123:8123 # HTTP interface
      - 9000:9000 # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  aihealth-nginx:
    container_name: aihealth-nginx
    build:
      context: "."
      dockerfile: "./deployment/nginx/Dockerfile"
    restart: no
    ports:
      - 80:80
      - 443:443
    depends_on:
      - aihealth-api
    volumes:
      - ssl_certs:/etc/ssl

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=aihealth-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - aihealth-mongo
    volumes:
      - ./config.js:/node_modules/mongo-express/config.default.js

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8084:8978"
    environment:
      - CB_ADMIN_NAME=cbadmin
      - CB_ADMIN_PASSWORD=Vostro@1540
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared

volumes:
  api_logs:
  api_data:
  redis_data:
  postgres_data:
  mongo_data:
  clickhouse_data:
  ssl_certs:
  redisinsight_data:
  cloudbeaver_workspace:
  portainer_data:


networks:
  shared_network:
    external: true
