services:

  aihealth-api:
    container_name: aihealth-api
    build:
      context: "."
      dockerfile: ./deployment/rest_server/Dockerfile
    image: aihealth-api:latest
    depends_on:
      - aihealth-redis
      - aihealth-postgres
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - JWT_ALGORITHM
      - JWT_SECRET
      - JWT_AUDIENCE
      - POSTGRES_URL
      - POSTGRES_SCHEMA
    volumes:
      - ./logs:/src/logs

  aihealth-redis:
    container_name: aihealth-redis
    image: redis:alpine
    command:
      - "-- requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    ports:
      - 6001:6379
    volumes:
      - ./deployment/volumes/redis:/data

  aihealth-postgres:
    container_name: aihealth-postgres
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    ports:
      - 5432:5432

