services:
  aihealth-api:
    container_name: aihealth-api
    build:
      context: "."
      dockerfile: ./deployment/rest_server/Dockerfile
    image: aihealth-api:latest
    depends_on:
      - aihealth-redis
      - aihealth-postgres
      - aihealth-mongo
      - aihealth-clickhouse
      - aihealth-qdrant
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_ALGORITHM
      - JWT_SECRET
      - JWT_AUDIENCE
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_ASYNCPG_URL=${POSTGRES_ASYNCPG_URL}
      - POSTGRES_URL_SYNC=${POSTGRES_URL_SYNC}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
    volumes:
      - api_logs:/src/logs
      - alembic_data:/src/alembic/versions
      # - ./src:/src # for dev use only
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G

  aihealth-celery:
    container_name: aihealth-celery
    image: aihealth-api:latest
    command: /opt/pysetup/.venv/bin/python -m celery -A lib.core.celery_app.celery worker --pool=custom --loglevel=info --concurrency=2
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_CUSTOM_WORKER_POOL=celery_aio_pool.pool:AsyncIOPool
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ASYNCPG_URL=${POSTGRES_ASYNCPG_URL}
    volumes:
      - celery_logs:/var/log/celery
      - celery_data:/var/lib/celery
    depends_on:
      - aihealth-redis
      - aihealth-api
    restart: unless-stopped
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1.5G

  aihealth-celery-beat:
    container_name: aihealth-celery-beat
    image: aihealth-api:latest
    command: /opt/pysetup/.venv/bin/python -m celery -A lib.core.celery_app.celery beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - POSTGRES_ASYNCPG_URL=${POSTGRES_ASYNCPG_URL}
    volumes:
      - celery_beat_logs:/var/log/celery
    depends_on:
      - aihealth-redis
      - aihealth-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512M

  aihealth-redis:
    container_name: aihealth-redis
    image: redis:alpine
    command:
      - "-- requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  aihealth-postgres:
    container_name: aihealth-postgres
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  aihealth-mongo:
    container_name: aihealth-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile/mongodb-keyfile
    restart: unless-stopped
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--auth",
        "--keyFile",
        "/etc/mongo-keyfile/mongodb-keyfile",
      ]
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "chown mongodb:mongodb /etc/mongo-keyfile/mongodb-keyfile && chmod 600 /etc/mongo-keyfile/mongodb-keyfile && exec mongod --replSet rs0 --bind_ip_all --port 27017 --auth --keyFile /etc/mongo-keyfile/mongodb-keyfile",
      ]

  aihealth-clickhouse:
    container_name: aihealth-clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123 # HTTP interface
      - 9000:9000 # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 1.5G

  aihealth-qdrant:
    container_name: aihealth-qdrant
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__MAX_WORKERS: 2
      QDRANT__STORAGE__CACHE_SIZE: 512MiB
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 1.5G

  aihealth-nginx:
    container_name: aihealth-nginx
    build:
      context: "."
      dockerfile: "./deployment/nginx/Dockerfile"
    restart: no
    ports:
      - 80:80
      - 443:443
    depends_on:
      - aihealth-api
    volumes:
      - ssl_certs:/etc/ssl

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  flower:
    image: mher/flower
    container_name: flower
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - aihealth-redis

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=aihealth-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - aihealth-mongo
    volumes:
      - ./config.js:/node_modules/mongo-express/config.default.js

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8084:8978"
    environment:
      - CB_ADMIN_NAME=${CB_ADMIN_NAME}
      - CB_ADMIN_PASSWORD=${CB_ADMIN_PASSWORD}
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared

volumes:
  api_logs:
  alembic_data:
  redis_data:
  postgres_data:
  mongo_data:
  clickhouse_data:
  qdrant_data:
  ssl_certs:
  redisinsight_data:
  cloudbeaver_workspace:
  portainer_data:
  pgadmin_data:
  celery_logs:
  celery_data:
  celery_beat_logs:

networks:
  shared_network:
    external: true
