server {
    listen 80;
    listen [::]:80;
    server_name api.aihealth.clinic;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # ssl_certificate             /etc/ssl/aihealth.clinic.ssl_cert.pem;
    # ssl_certificate_key         /etc/ssl/aihealth.clinic.ssl_key.key;  
    # ssl_client_certificate      /etc/ssl/cloudflare.crt;
    # ssl_verify_client on;

    server_name api.aihealth.clinic;

    access_log  /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    proxy_read_timeout 60;
    proxy_connect_timeout 60;
    proxy_send_timeout 60;
    send_timeout 60;

    location / {
        proxy_pass         "http://aihealth-api:8000";
        proxy_redirect     off;

        proxy_set_header   Host                 $http_host;
        proxy_set_header   X-Real-IP            $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
