"""Initial migration

Revision ID: 5df336faacba
Revises: 
Create Date: 2024-07-11 04:16:56.664290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df336faacba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('alcohol_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('consume_alcohol', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('type_of_alcohol', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcohol_consumption_id'), 'alcohol_consumption', ['id'], unique=False)
    op.create_table('cuisine_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cuisine', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuisine_preferences_id'), 'cuisine_preferences', ['id'], unique=False)
    op.create_table('current_medication',
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('has_medication', sa.Boolean(), nullable=True),
    sa.Column('prescription_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_index(op.f('ix_current_medication_medication_id'), 'current_medication', ['medication_id'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activity_id'), 'daily_activity', ['id'], unique=False)
    op.create_table('diabetic_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of_diabetes', sa.String(length=50), nullable=True),
    sa.Column('years_with_diabetes', sa.Integer(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('pregnancy_weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('diet_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('family_diabetic_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('family_member', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_family_diabetic_history_history_id'), 'family_diabetic_history', ['history_id'], unique=False)
    op.create_table('food_allergies',
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('allergy_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('allergy_id')
    )
    op.create_index(op.f('ix_food_allergies_allergy_id'), 'food_allergies', ['allergy_id'], unique=False)
    op.create_table('meal_timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timing', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_timings_id'), 'meal_timings', ['id'], unique=False)
    op.create_table('medical_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_medical_history_history_id'), 'medical_history', ['history_id'], unique=False)
    op.create_table('medicine_allergies',
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('allergy_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('allergy_id')
    )
    op.create_index(op.f('ix_medicine_allergies_allergy_id'), 'medicine_allergies', ['allergy_id'], unique=False)
    op.create_table('sleep_summary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.String(length=50), nullable=True),
    sa.Column('wake_up_fresh', sa.Boolean(), nullable=True),
    sa.Column('drowsy_day', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('smoking_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('smoke_status', sa.String(length=20), nullable=True),
    sa.Column('years_of_smoking', sa.Integer(), nullable=True),
    sa.Column('cigarettes_per_day', sa.Integer(), nullable=True),
    sa.Column('quit_years_ago', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smoking_habits_id'), 'smoking_habits', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('prescription_file', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['current_medication.medication_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_prescriptions_prescription_id'), 'prescriptions', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_prescription_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_smoking_habits_id'), table_name='smoking_habits')
    op.drop_table('smoking_habits')
    op.drop_table('sleep_summary')
    op.drop_index(op.f('ix_medicine_allergies_allergy_id'), table_name='medicine_allergies')
    op.drop_table('medicine_allergies')
    op.drop_index(op.f('ix_medical_history_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_meal_timings_id'), table_name='meal_timings')
    op.drop_table('meal_timings')
    op.drop_index(op.f('ix_food_allergies_allergy_id'), table_name='food_allergies')
    op.drop_table('food_allergies')
    op.drop_index(op.f('ix_family_diabetic_history_history_id'), table_name='family_diabetic_history')
    op.drop_table('family_diabetic_history')
    op.drop_table('diet_preferences')
    op.drop_table('diabetic_history')
    op.drop_index(op.f('ix_daily_activity_id'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_current_medication_medication_id'), table_name='current_medication')
    op.drop_table('current_medication')
    op.drop_index(op.f('ix_cuisine_preferences_id'), table_name='cuisine_preferences')
    op.drop_table('cuisine_preferences')
    op.drop_index(op.f('ix_alcohol_consumption_id'), table_name='alcohol_consumption')
    op.drop_table('alcohol_consumption')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
