"""Constants for meal report processing."""

HIGH_CARB_THRESHOLD = 60
LOW_PROTEIN_THRESHOLD = 10
LOW_FIBER_THRESHOLD = 3

CARB_MIN, CARB_MAX = 45, 65
PROTEIN_MIN, PROTEIN_MAX = 15, 40
FAT_MIN, FAT_MAX = 20, 35
FIBER_MIN, FIBER_MAX = 8, 15

CARB_ENERGY_PER_GRAM = 4
PROTEIN_ENERGY_PER_GRAM = 4
FAT_ENERGY_PER_GRAM = 9
