"""Achievement definitions — seeded into the achievements table."""

from __future__ import annotations

from typing import Any, Dict, List

ACHIEVEMENT_CATALOG: List[Dict[str, Any]] = [
    # ── Consistency ──────────────────────────────────────────────────────
    {"slug": "streak_3", "title": "Getting Started", "description": "Maintain a 3-day streak", "icon": "streak_bronze", "category": "consistency", "tier": "bronze", "xp_reward": 25, "criteria_type": "streak_days", "criteria_threshold": 3, "sort_order": 10},
    {"slug": "streak_7", "title": "Week Warrior", "description": "Maintain a 7-day streak", "icon": "streak_bronze", "category": "consistency", "tier": "bronze", "xp_reward": 50, "criteria_type": "streak_days", "criteria_threshold": 7, "sort_order": 11},
    {"slug": "streak_14", "title": "Two Week Strong", "description": "Maintain a 14-day streak", "icon": "streak_silver", "category": "consistency", "tier": "silver", "xp_reward": 100, "criteria_type": "streak_days", "criteria_threshold": 14, "sort_order": 12},
    {"slug": "streak_30", "title": "Monthly Champion", "description": "Maintain a 30-day streak", "icon": "streak_gold", "category": "consistency", "tier": "gold", "xp_reward": 200, "criteria_type": "streak_days", "criteria_threshold": 30, "sort_order": 13},
    {"slug": "streak_60", "title": "Iron Will", "description": "Maintain a 60-day streak", "icon": "streak_gold", "category": "consistency", "tier": "gold", "xp_reward": 400, "criteria_type": "streak_days", "criteria_threshold": 60, "sort_order": 14},
    {"slug": "streak_90", "title": "Legendary Streak", "description": "Maintain a 90-day streak", "icon": "streak_platinum", "category": "consistency", "tier": "platinum", "xp_reward": 750, "criteria_type": "streak_days", "criteria_threshold": 90, "sort_order": 15},
    {"slug": "monthly_25", "title": "Monthly Warrior", "description": "Be active 25+ days in a calendar month", "icon": "calendar_silver", "category": "consistency", "tier": "silver", "xp_reward": 150, "criteria_type": "monthly_active_days", "criteria_threshold": 25, "sort_order": 16},
    # ── Nutrition ────────────────────────────────────────────────────────
    {"slug": "meals_1", "title": "First Bite", "description": "Log your first meal", "icon": "meal_bronze", "category": "nutrition", "tier": "bronze", "xp_reward": 10, "criteria_type": "meals_logged", "criteria_threshold": 1, "is_progressive": True, "progressive_group": "meals", "sort_order": 20},
    {"slug": "meals_50", "title": "Meal Logger", "description": "Log 50 meals", "icon": "meal_bronze", "category": "nutrition", "tier": "bronze", "xp_reward": 50, "criteria_type": "meals_logged", "criteria_threshold": 50, "is_progressive": True, "progressive_group": "meals", "sort_order": 21},
    {"slug": "meals_200", "title": "Nutrition Nerd", "description": "Log 200 meals", "icon": "meal_silver", "category": "nutrition", "tier": "silver", "xp_reward": 100, "criteria_type": "meals_logged", "criteria_threshold": 200, "is_progressive": True, "progressive_group": "meals", "sort_order": 22},
    {"slug": "meals_500", "title": "Meal Master", "description": "Log 500 meals", "icon": "meal_gold", "category": "nutrition", "tier": "gold", "xp_reward": 250, "criteria_type": "meals_logged", "criteria_threshold": 500, "is_progressive": True, "progressive_group": "meals", "sort_order": 23},
    {"slug": "macro_hit_3", "title": "Macro Beginner", "description": "Hit your macro targets 3 days in a row", "icon": "macro_bronze", "category": "nutrition", "tier": "bronze", "xp_reward": 30, "criteria_type": "macro_hit_streak", "criteria_threshold": 3, "is_progressive": True, "progressive_group": "macro_hit", "sort_order": 24},
    {"slug": "macro_hit_14", "title": "Macro Consistent", "description": "Hit your macro targets 14 days in a row", "icon": "macro_silver", "category": "nutrition", "tier": "silver", "xp_reward": 100, "criteria_type": "macro_hit_streak", "criteria_threshold": 14, "is_progressive": True, "progressive_group": "macro_hit", "sort_order": 25},
    {"slug": "macro_hit_30", "title": "Macro Master", "description": "Hit your macro targets 30 days in a row", "icon": "macro_gold", "category": "nutrition", "tier": "gold", "xp_reward": 200, "criteria_type": "macro_hit_streak", "criteria_threshold": 30, "is_progressive": True, "progressive_group": "macro_hit", "sort_order": 26},
    # ── Fitness ──────────────────────────────────────────────────────────
    {"slug": "steps_first", "title": "First Steps", "description": "Hit your step goal for the first time", "icon": "steps_bronze", "category": "fitness", "tier": "bronze", "xp_reward": 10, "criteria_type": "steps_hit", "criteria_threshold": 1, "is_progressive": True, "progressive_group": "steps", "sort_order": 30},
    {"slug": "steps_7", "title": "Step Machine", "description": "Hit your step goal 7 days", "icon": "steps_bronze", "category": "fitness", "tier": "bronze", "xp_reward": 50, "criteria_type": "steps_hit", "criteria_threshold": 7, "is_progressive": True, "progressive_group": "steps", "sort_order": 31},
    {"slug": "steps_30", "title": "Walking Legend", "description": "Hit your step goal 30 days", "icon": "steps_gold", "category": "fitness", "tier": "gold", "xp_reward": 200, "criteria_type": "steps_hit", "criteria_threshold": 30, "is_progressive": True, "progressive_group": "steps", "sort_order": 32},
    {"slug": "workouts_1", "title": "First Workout", "description": "Complete your first planned workout", "icon": "workout_bronze", "category": "fitness", "tier": "bronze", "xp_reward": 10, "criteria_type": "workouts_completed", "criteria_threshold": 1, "is_progressive": True, "progressive_group": "workouts", "sort_order": 33},
    {"slug": "workouts_10", "title": "Gym Regular", "description": "Complete 10 planned workouts", "icon": "workout_bronze", "category": "fitness", "tier": "bronze", "xp_reward": 50, "criteria_type": "workouts_completed", "criteria_threshold": 10, "is_progressive": True, "progressive_group": "workouts", "sort_order": 34},
    {"slug": "workouts_50", "title": "Workout Warrior", "description": "Complete 50 planned workouts", "icon": "workout_silver", "category": "fitness", "tier": "silver", "xp_reward": 150, "criteria_type": "workouts_completed", "criteria_threshold": 50, "is_progressive": True, "progressive_group": "workouts", "sort_order": 35},
    {"slug": "workouts_200", "title": "Iron Athlete", "description": "Complete 200 planned workouts", "icon": "workout_gold", "category": "fitness", "tier": "gold", "xp_reward": 400, "criteria_type": "workouts_completed", "criteria_threshold": 200, "is_progressive": True, "progressive_group": "workouts", "sort_order": 36},
    # ── Wellness ─────────────────────────────────────────────────────────
    {"slug": "mood_7", "title": "Mindful Week", "description": "Log your mood for 7 days", "icon": "mood_bronze", "category": "wellness", "tier": "bronze", "xp_reward": 40, "criteria_type": "mood_logged", "criteria_threshold": 7, "sort_order": 40},
    {"slug": "mood_30", "title": "Emotional Awareness", "description": "Log your mood for 30 days", "icon": "mood_silver", "category": "wellness", "tier": "silver", "xp_reward": 100, "criteria_type": "mood_logged", "criteria_threshold": 30, "sort_order": 41},
    {"slug": "sleep_14", "title": "Sleep Scholar", "description": "Log your sleep for 14 days", "icon": "sleep_silver", "category": "wellness", "tier": "silver", "xp_reward": 75, "criteria_type": "sleep_logged", "criteria_threshold": 14, "sort_order": 42},
    # ── Social ───────────────────────────────────────────────────────────
    {"slug": "first_buddy", "title": "Better Together", "description": "Add your first buddy", "icon": "buddy_bronze", "category": "social", "tier": "bronze", "xp_reward": 25, "criteria_type": "buddy_added", "criteria_threshold": 1, "sort_order": 50},
    {"slug": "cheers_10", "title": "Cheerleader", "description": "Send 10 cheers to friends", "icon": "cheer_bronze", "category": "social", "tier": "bronze", "xp_reward": 30, "criteria_type": "cheers_sent", "criteria_threshold": 10, "sort_order": 51},
    {"slug": "cheers_100", "title": "Hype Machine", "description": "Send 100 cheers to friends", "icon": "cheer_silver", "category": "social", "tier": "silver", "xp_reward": 100, "criteria_type": "cheers_sent", "criteria_threshold": 100, "sort_order": 52},
    {"slug": "group_challenge_1", "title": "Team Player", "description": "Complete your first group challenge", "icon": "team_bronze", "category": "social", "tier": "bronze", "xp_reward": 50, "criteria_type": "group_challenges_completed", "criteria_threshold": 1, "sort_order": 53},
    {"slug": "group_challenge_10", "title": "Team Leader", "description": "Complete 10 group challenges", "icon": "team_silver", "category": "social", "tier": "silver", "xp_reward": 150, "criteria_type": "group_challenges_completed", "criteria_threshold": 10, "sort_order": 54},
    {"slug": "buddy_streak_7", "title": "Accountability Duo", "description": "Both you and your buddy active for 7 days straight", "icon": "buddy_silver", "category": "social", "tier": "silver", "xp_reward": 75, "criteria_type": "buddy_streak", "criteria_threshold": 7, "sort_order": 55},
    {"slug": "buddy_streak_30", "title": "Inseparable", "description": "Both you and your buddy active for 30 days straight", "icon": "buddy_gold", "category": "social", "tier": "gold", "xp_reward": 200, "criteria_type": "buddy_streak", "criteria_threshold": 30, "sort_order": 56},
    # ── Milestones ───────────────────────────────────────────────────────
    {"slug": "level_5", "title": "Rising Star", "description": "Reach level 5", "icon": "level_bronze", "category": "milestone", "tier": "bronze", "xp_reward": 50, "criteria_type": "level_reached", "criteria_threshold": 5, "sort_order": 60},
    {"slug": "level_10", "title": "Double Digits", "description": "Reach level 10", "icon": "level_silver", "category": "milestone", "tier": "silver", "xp_reward": 100, "criteria_type": "level_reached", "criteria_threshold": 10, "sort_order": 61},
    {"slug": "level_20", "title": "Dedicated", "description": "Reach level 20", "icon": "level_gold", "category": "milestone", "tier": "gold", "xp_reward": 200, "criteria_type": "level_reached", "criteria_threshold": 20, "sort_order": 62},
    {"slug": "level_50", "title": "Legend", "description": "Reach level 50", "icon": "level_platinum", "category": "milestone", "tier": "platinum", "xp_reward": 500, "criteria_type": "level_reached", "criteria_threshold": 50, "sort_order": 63},
    {"slug": "tasks_100", "title": "Century", "description": "Complete 100 tasks", "icon": "task_silver", "category": "milestone", "tier": "silver", "xp_reward": 100, "criteria_type": "tasks_completed", "criteria_threshold": 100, "sort_order": 64},
    {"slug": "tasks_500", "title": "Five Hundred Club", "description": "Complete 500 tasks", "icon": "task_gold", "category": "milestone", "tier": "gold", "xp_reward": 250, "criteria_type": "tasks_completed", "criteria_threshold": 500, "sort_order": 65},
    {"slug": "tasks_1000", "title": "Thousand Club", "description": "Complete 1000 tasks", "icon": "task_platinum", "category": "milestone", "tier": "platinum", "xp_reward": 500, "criteria_type": "tasks_completed", "criteria_threshold": 1000, "sort_order": 66},
    {"slug": "xp_10000", "title": "XP Hoarder", "description": "Earn 10,000 total XP", "icon": "xp_silver", "category": "milestone", "tier": "silver", "xp_reward": 100, "criteria_type": "total_xp", "criteria_threshold": 10000, "sort_order": 67},
    {"slug": "xp_50000", "title": "XP Vault", "description": "Earn 50,000 total XP", "icon": "xp_gold", "category": "milestone", "tier": "gold", "xp_reward": 250, "criteria_type": "total_xp", "criteria_threshold": 50000, "sort_order": 68},
    # ── Hidden ───────────────────────────────────────────────────────────
    {"slug": "night_owl", "title": "Night Owl", "description": "Log something at 3 AM", "icon": "hidden_owl", "category": "consistency", "tier": "bronze", "xp_reward": 15, "criteria_type": "custom", "criteria_threshold": 1, "is_hidden": True, "sort_order": 90},
    {"slug": "comeback_kid", "title": "Comeback Kid", "description": "Rebuild your streak after losing one", "icon": "hidden_comeback", "category": "consistency", "tier": "silver", "xp_reward": 50, "criteria_type": "custom", "criteria_threshold": 1, "is_hidden": True, "sort_order": 91},
    {"slug": "perfect_week", "title": "Perfect Week", "description": "Complete every plan-derived task for a full week", "icon": "hidden_perfect", "category": "consistency", "tier": "gold", "xp_reward": 200, "criteria_type": "custom", "criteria_threshold": 1, "is_hidden": True, "sort_order": 92},
    {"slug": "early_bird", "title": "Early Bird", "description": "Log before 6 AM for 7 days", "icon": "hidden_early", "category": "consistency", "tier": "bronze", "xp_reward": 30, "criteria_type": "custom", "criteria_threshold": 7, "is_hidden": True, "sort_order": 93},
    {"slug": "social_butterfly", "title": "Social Butterfly", "description": "Be in 3 or more groups simultaneously", "icon": "hidden_social", "category": "social", "tier": "bronze", "xp_reward": 25, "criteria_type": "custom", "criteria_threshold": 3, "is_hidden": True, "sort_order": 94},
]
